source 'https://github.com/lhp3851/Stack_APP.git'
#https://github.com/lhp3851/Components.git
#https://github.com/lhp3851/Stack_APP.git
platform :ios, '9.3.0'
use_frameworks!

target 'Components_Example' do
  pod 'Components', :path => '../'

  target 'Components_Tests' do
    inherit! :search_paths

    
  end
end
